/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PilotConsultationRouteImport } from './routes/pilot-consultation'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ConsultationBookingRouteImport } from './routes/consultation-booking'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiCoWorkersRouteImport } from './routes/ai-co-workers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SolutionsOrderToCashRouteImport } from './routes/solutions.order-to-cash'
import { Route as SolutionsItsmRouteImport } from './routes/solutions.itsm'
import { Route as SolutionsFinanceRouteImport } from './routes/solutions.finance'
import { Route as SolutionsClaimsRouteImport } from './routes/solutions.claims'
import { Route as CaseStudiesWesternSouthernRouteImport } from './routes/case-studies.western-southern'
import { Route as CaseStudiesCampariRouteImport } from './routes/case-studies.campari'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminPostsIdRouteImport } from './routes/_authenticated/admin.posts.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotConsultationRoute = PilotConsultationRouteImport.update({
  id: '/pilot-consultation',
  path: '/pilot-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationBookingRoute = ConsultationBookingRouteImport.update({
  id: '/consultation-booking',
  path: '/consultation-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCoWorkersRoute = AiCoWorkersRouteImport.update({
  id: '/ai-co-workers',
  path: '/ai-co-workers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsOrderToCashRoute = SolutionsOrderToCashRouteImport.update({
  id: '/solutions/order-to-cash',
  path: '/solutions/order-to-cash',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsItsmRoute = SolutionsItsmRouteImport.update({
  id: '/solutions/itsm',
  path: '/solutions/itsm',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFinanceRoute = SolutionsFinanceRouteImport.update({
  id: '/solutions/finance',
  path: '/solutions/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsClaimsRoute = SolutionsClaimsRouteImport.update({
  id: '/solutions/claims',
  path: '/solutions/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesWesternSouthernRoute =
  CaseStudiesWesternSouthernRouteImport.update({
    id: '/case-studies/western-southern',
    path: '/case-studies/western-southern',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesCampariRoute = CaseStudiesCampariRouteImport.update({
  id: '/case-studies/campari',
  path: '/case-studies/campari',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPostsIdRoute =
  AuthenticatedAdminPostsIdRouteImport.update({
    id: '/posts/$id',
    path: '/posts/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-co-workers': typeof AiCoWorkersRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/consultation-booking': typeof ConsultationBookingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pilot-consultation': typeof PilotConsultationRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/campari': typeof CaseStudiesCampariRoute
  '/case-studies/western-southern': typeof CaseStudiesWesternSouthernRoute
  '/solutions/claims': typeof SolutionsClaimsRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/order-to-cash': typeof SolutionsOrderToCashRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-co-workers': typeof AiCoWorkersRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/consultation-booking': typeof ConsultationBookingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pilot-consultation': typeof PilotConsultationRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/campari': typeof CaseStudiesCampariRoute
  '/case-studies/western-southern': typeof CaseStudiesWesternSouthernRoute
  '/solutions/claims': typeof SolutionsClaimsRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/order-to-cash': typeof SolutionsOrderToCashRoute
  '/blog': typeof BlogIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/ai-co-workers': typeof AiCoWorkersRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/consultation-booking': typeof ConsultationBookingRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pilot-consultation': typeof PilotConsultationRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/campari': typeof CaseStudiesCampariRoute
  '/case-studies/western-southern': typeof CaseStudiesWesternSouthernRoute
  '/solutions/claims': typeof SolutionsClaimsRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/order-to-cash': typeof SolutionsOrderToCashRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/posts/$id': typeof AuthenticatedAdminPostsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-co-workers'
    | '/auth'
    | '/careers'
    | '/consultation-booking'
    | '/how-it-works'
    | '/pilot-consultation'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/blog/$slug'
    | '/case-studies/campari'
    | '/case-studies/western-southern'
    | '/solutions/claims'
    | '/solutions/finance'
    | '/solutions/itsm'
    | '/solutions/order-to-cash'
    | '/blog/'
    | '/admin/'
    | '/admin/posts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-co-workers'
    | '/auth'
    | '/careers'
    | '/consultation-booking'
    | '/how-it-works'
    | '/pilot-consultation'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/case-studies/campari'
    | '/case-studies/western-southern'
    | '/solutions/claims'
    | '/solutions/finance'
    | '/solutions/itsm'
    | '/solutions/order-to-cash'
    | '/blog'
    | '/admin'
    | '/admin/posts/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/ai-co-workers'
    | '/auth'
    | '/careers'
    | '/consultation-booking'
    | '/how-it-works'
    | '/pilot-consultation'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/case-studies/campari'
    | '/case-studies/western-southern'
    | '/solutions/claims'
    | '/solutions/finance'
    | '/solutions/itsm'
    | '/solutions/order-to-cash'
    | '/blog/'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/posts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AiCoWorkersRoute: typeof AiCoWorkersRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ConsultationBookingRoute: typeof ConsultationBookingRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PilotConsultationRoute: typeof PilotConsultationRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CaseStudiesCampariRoute: typeof CaseStudiesCampariRoute
  CaseStudiesWesternSouthernRoute: typeof CaseStudiesWesternSouthernRoute
  SolutionsClaimsRoute: typeof SolutionsClaimsRoute
  SolutionsFinanceRoute: typeof SolutionsFinanceRoute
  SolutionsItsmRoute: typeof SolutionsItsmRoute
  SolutionsOrderToCashRoute: typeof SolutionsOrderToCashRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot-consultation': {
      id: '/pilot-consultation'
      path: '/pilot-consultation'
      fullPath: '/pilot-consultation'
      preLoaderRoute: typeof PilotConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation-booking': {
      id: '/consultation-booking'
      path: '/consultation-booking'
      fullPath: '/consultation-booking'
      preLoaderRoute: typeof ConsultationBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-co-workers': {
      id: '/ai-co-workers'
      path: '/ai-co-workers'
      fullPath: '/ai-co-workers'
      preLoaderRoute: typeof AiCoWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/order-to-cash': {
      id: '/solutions/order-to-cash'
      path: '/solutions/order-to-cash'
      fullPath: '/solutions/order-to-cash'
      preLoaderRoute: typeof SolutionsOrderToCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/itsm': {
      id: '/solutions/itsm'
      path: '/solutions/itsm'
      fullPath: '/solutions/itsm'
      preLoaderRoute: typeof SolutionsItsmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/finance': {
      id: '/solutions/finance'
      path: '/solutions/finance'
      fullPath: '/solutions/finance'
      preLoaderRoute: typeof SolutionsFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/claims': {
      id: '/solutions/claims'
      path: '/solutions/claims'
      fullPath: '/solutions/claims'
      preLoaderRoute: typeof SolutionsClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/western-southern': {
      id: '/case-studies/western-southern'
      path: '/case-studies/western-southern'
      fullPath: '/case-studies/western-southern'
      preLoaderRoute: typeof CaseStudiesWesternSouthernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/campari': {
      id: '/case-studies/campari'
      path: '/case-studies/campari'
      fullPath: '/case-studies/campari'
      preLoaderRoute: typeof CaseStudiesCampariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts/$id': {
      id: '/_authenticated/admin/posts/$id'
      path: '/posts/$id'
      fullPath: '/admin/posts/$id'
      preLoaderRoute: typeof AuthenticatedAdminPostsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPostsIdRoute: typeof AuthenticatedAdminPostsIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPostsIdRoute: AuthenticatedAdminPostsIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AiCoWorkersRoute: AiCoWorkersRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ConsultationBookingRoute: ConsultationBookingRoute,
  HowItWorksRoute: HowItWorksRoute,
  PilotConsultationRoute: PilotConsultationRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CaseStudiesCampariRoute: CaseStudiesCampariRoute,
  CaseStudiesWesternSouthernRoute: CaseStudiesWesternSouthernRoute,
  SolutionsClaimsRoute: SolutionsClaimsRoute,
  SolutionsFinanceRoute: SolutionsFinanceRoute,
  SolutionsItsmRoute: SolutionsItsmRoute,
  SolutionsOrderToCashRoute: SolutionsOrderToCashRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
