/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PilotConsultationRouteImport } from './routes/pilot-consultation'
import { Route as ConsultationBookingRouteImport } from './routes/consultation-booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiCoWorkersRouteImport } from './routes/ai-co-workers'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SolutionsOrderToCashRouteImport } from './routes/solutions.order-to-cash'
import { Route as SolutionsItsmRouteImport } from './routes/solutions.itsm'
import { Route as SolutionsFinanceRouteImport } from './routes/solutions.finance'
import { Route as SolutionsClaimsRouteImport } from './routes/solutions.claims'
import { Route as CaseStudiesCampariRouteImport } from './routes/case-studies.campari'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotConsultationRoute = PilotConsultationRouteImport.update({
  id: '/pilot-consultation',
  path: '/pilot-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationBookingRoute = ConsultationBookingRouteImport.update({
  id: '/consultation-booking',
  path: '/consultation-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCoWorkersRoute = AiCoWorkersRouteImport.update({
  id: '/ai-co-workers',
  path: '/ai-co-workers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsOrderToCashRoute = SolutionsOrderToCashRouteImport.update({
  id: '/solutions/order-to-cash',
  path: '/solutions/order-to-cash',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsItsmRoute = SolutionsItsmRouteImport.update({
  id: '/solutions/itsm',
  path: '/solutions/itsm',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFinanceRoute = SolutionsFinanceRouteImport.update({
  id: '/solutions/finance',
  path: '/solutions/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsClaimsRoute = SolutionsClaimsRouteImport.update({
  id: '/solutions/claims',
  path: '/solutions/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesCampariRoute = CaseStudiesCampariRouteImport.update({
  id: '/case-studies/campari',
  path: '/case-studies/campari',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-co-workers': typeof AiCoWorkersRoute
  '/auth': typeof AuthRoute
  '/consultation-booking': typeof ConsultationBookingRoute
  '/pilot-consultation': typeof PilotConsultationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/campari': typeof CaseStudiesCampariRoute
  '/solutions/claims': typeof SolutionsClaimsRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/order-to-cash': typeof SolutionsOrderToCashRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-co-workers': typeof AiCoWorkersRoute
  '/auth': typeof AuthRoute
  '/consultation-booking': typeof ConsultationBookingRoute
  '/pilot-consultation': typeof PilotConsultationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/campari': typeof CaseStudiesCampariRoute
  '/solutions/claims': typeof SolutionsClaimsRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/order-to-cash': typeof SolutionsOrderToCashRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-co-workers': typeof AiCoWorkersRoute
  '/auth': typeof AuthRoute
  '/consultation-booking': typeof ConsultationBookingRoute
  '/pilot-consultation': typeof PilotConsultationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/campari': typeof CaseStudiesCampariRoute
  '/solutions/claims': typeof SolutionsClaimsRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/itsm': typeof SolutionsItsmRoute
  '/solutions/order-to-cash': typeof SolutionsOrderToCashRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-co-workers'
    | '/auth'
    | '/consultation-booking'
    | '/pilot-consultation'
    | '/sitemap.xml'
    | '/admin'
    | '/blog/$slug'
    | '/case-studies/campari'
    | '/solutions/claims'
    | '/solutions/finance'
    | '/solutions/itsm'
    | '/solutions/order-to-cash'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-co-workers'
    | '/auth'
    | '/consultation-booking'
    | '/pilot-consultation'
    | '/sitemap.xml'
    | '/admin'
    | '/blog/$slug'
    | '/case-studies/campari'
    | '/solutions/claims'
    | '/solutions/finance'
    | '/solutions/itsm'
    | '/solutions/order-to-cash'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-co-workers'
    | '/auth'
    | '/consultation-booking'
    | '/pilot-consultation'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/blog/$slug'
    | '/case-studies/campari'
    | '/solutions/claims'
    | '/solutions/finance'
    | '/solutions/itsm'
    | '/solutions/order-to-cash'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiCoWorkersRoute: typeof AiCoWorkersRoute
  AuthRoute: typeof AuthRoute
  ConsultationBookingRoute: typeof ConsultationBookingRoute
  PilotConsultationRoute: typeof PilotConsultationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CaseStudiesCampariRoute: typeof CaseStudiesCampariRoute
  SolutionsClaimsRoute: typeof SolutionsClaimsRoute
  SolutionsFinanceRoute: typeof SolutionsFinanceRoute
  SolutionsItsmRoute: typeof SolutionsItsmRoute
  SolutionsOrderToCashRoute: typeof SolutionsOrderToCashRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot-consultation': {
      id: '/pilot-consultation'
      path: '/pilot-consultation'
      fullPath: '/pilot-consultation'
      preLoaderRoute: typeof PilotConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation-booking': {
      id: '/consultation-booking'
      path: '/consultation-booking'
      fullPath: '/consultation-booking'
      preLoaderRoute: typeof ConsultationBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-co-workers': {
      id: '/ai-co-workers'
      path: '/ai-co-workers'
      fullPath: '/ai-co-workers'
      preLoaderRoute: typeof AiCoWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/order-to-cash': {
      id: '/solutions/order-to-cash'
      path: '/solutions/order-to-cash'
      fullPath: '/solutions/order-to-cash'
      preLoaderRoute: typeof SolutionsOrderToCashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/itsm': {
      id: '/solutions/itsm'
      path: '/solutions/itsm'
      fullPath: '/solutions/itsm'
      preLoaderRoute: typeof SolutionsItsmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/finance': {
      id: '/solutions/finance'
      path: '/solutions/finance'
      fullPath: '/solutions/finance'
      preLoaderRoute: typeof SolutionsFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/claims': {
      id: '/solutions/claims'
      path: '/solutions/claims'
      fullPath: '/solutions/claims'
      preLoaderRoute: typeof SolutionsClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/campari': {
      id: '/case-studies/campari'
      path: '/case-studies/campari'
      fullPath: '/case-studies/campari'
      preLoaderRoute: typeof CaseStudiesCampariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiCoWorkersRoute: AiCoWorkersRoute,
  AuthRoute: AuthRoute,
  ConsultationBookingRoute: ConsultationBookingRoute,
  PilotConsultationRoute: PilotConsultationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  CaseStudiesCampariRoute: CaseStudiesCampariRoute,
  SolutionsClaimsRoute: SolutionsClaimsRoute,
  SolutionsFinanceRoute: SolutionsFinanceRoute,
  SolutionsItsmRoute: SolutionsItsmRoute,
  SolutionsOrderToCashRoute: SolutionsOrderToCashRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
